// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by SoftDreams Developer
// **************************************************************************
// ignore_for_file: constant_identifier_names, non_constant_identifier_names

class Assets {
  const Assets._();
  static const String package = 'ecert';

  static bool isFromModules = false;

  /// {@macro assets_generator.ASSETS_ECERT_BG_DETAIL_CTS_SVG.preview}
  static String get ASSETS_ECERT_BG_DETAIL_CTS_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/BG_detail_CTS.svg';

  /// {@macro assets_generator.ASSETS_ECERT_FILTER_TIME_SVG.preview}
  static String get ASSETS_ECERT_FILTER_TIME_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/Filter_time.svg';

  /// {@macro assets_generator.ASSETS_ECERT_HOMECTS_SVG.preview}
  static String get ASSETS_ECERT_HOMECTS_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/HomeCTS.svg';

  /// {@macro assets_generator.ASSETS_ECERT_HOMECTS_SELECT_SVG.preview}
  static String get ASSETS_ECERT_HOMECTS_SELECT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/HomeCTS_select.svg';

  /// {@macro assets_generator.ASSETS_ECERT_HOME_SELECT_SVG.preview}
  static String get ASSETS_ECERT_HOME_SELECT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/Home_select.svg';

  /// {@macro assets_generator.ASSETS_ECERT_HOME_UNSELECT_SVG.preview}
  static String get ASSETS_ECERT_HOME_UNSELECT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/Home_unselect.svg';

  /// {@macro assets_generator.ASSETS_ECERT_LOCK_SVG.preview}
  static String get ASSETS_ECERT_LOCK_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/Lock.svg';

  /// {@macro assets_generator.ASSETS_ECERT_LOGINBACKGROUND_PNG.preview}
  static String get ASSETS_ECERT_LOGINBACKGROUND_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/LoginBackground.png';

  /// {@macro assets_generator.ASSETS_ECERT_LOGOUT_SVG.preview}
  static String get ASSETS_ECERT_LOGOUT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/Logout.svg';

  /// {@macro assets_generator.ASSETS_ECERT_MONTH_CHEVRON_SVG.preview}
  static String get ASSETS_ECERT_MONTH_CHEVRON_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/Month Chevron.svg';

  /// {@macro assets_generator.ASSETS_ECERT_NFC_PNG.preview}
  static String get ASSETS_ECERT_NFC_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/NFC.png';

  /// {@macro assets_generator.ASSETS_ECERT_SHIELD_DONE_SVG.preview}
  static String get ASSETS_ECERT_SHIELD_DONE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/Shield Done.svg';

  /// {@macro assets_generator.ASSETS_ECERT_VECTOR_SVG.preview}
  static String get ASSETS_ECERT_VECTOR_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/Vector.svg';

  /// {@macro assets_generator.ASSETS_ECERT_ACCOUNT_USER_AVATAR_SVGREPO_COM_1_SVG.preview}
  static String get ASSETS_ECERT_ACCOUNT_USER_AVATAR_SVGREPO_COM_1_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/account-user-avatar-svgrepo-com 1.svg';

  /// {@macro assets_generator.ASSETS_ECERT_ACTIVE_SVG.preview}
  static String get ASSETS_ECERT_ACTIVE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/active.svg';

  /// {@macro assets_generator.ASSETS_ECERT_ADDRESS_SVG.preview}
  static String get ASSETS_ECERT_ADDRESS_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/address.svg';

  /// {@macro assets_generator.ASSETS_ECERT_CALENDAR_SVG.preview}
  static String get ASSETS_ECERT_CALENDAR_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/calendar.svg';

  /// {@macro assets_generator.ASSETS_ECERT_CAMERA_FILL_BORDER_SVG.preview}
  static String get ASSETS_ECERT_CAMERA_FILL_BORDER_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/camera-fill-border.svg';

  /// {@macro assets_generator.ASSETS_ECERT_CAMERA_FILL_SVG.preview}
  static String get ASSETS_ECERT_CAMERA_FILL_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/camera-fill.svg';

  /// {@macro assets_generator.ASSETS_ECERT_CHANGE_SVG.preview}
  static String get ASSETS_ECERT_CHANGE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/change.svg';

  /// {@macro assets_generator.ASSETS_ECERT_CHECK_CIRCLE_SVG.preview}
  static String get ASSETS_ECERT_CHECK_CIRCLE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/check circle.svg';

  /// {@macro assets_generator.ASSETS_ECERT_CLOCK_SVG.preview}
  static String get ASSETS_ECERT_CLOCK_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/clock.svg';

  /// {@macro assets_generator.ASSETS_ECERT_DETAICTS_SVG.preview}
  static String get ASSETS_ECERT_DETAICTS_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/detaiCTS.svg';

  /// {@macro assets_generator.ASSETS_ECERT_DROPDOWN_SVG.preview}
  static String get ASSETS_ECERT_DROPDOWN_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/dropdown.svg';

  /// {@macro assets_generator.ASSETS_ECERT_EXCLAMATION_CIRCLE_SVG.preview}
  static String get ASSETS_ECERT_EXCLAMATION_CIRCLE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/exclamation circle.svg';

  /// {@macro assets_generator.ASSETS_ECERT_EYE_FILL_SVG.preview}
  static String get ASSETS_ECERT_EYE_FILL_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/eye-fill.svg';

  /// {@macro assets_generator.ASSETS_ECERT_EYE_OFF_FILL_SVG.preview}
  static String get ASSETS_ECERT_EYE_OFF_FILL_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/eye-off-fill.svg';

  /// {@macro assets_generator.ASSETS_ECERT_FILTER_SVG.preview}
  static String get ASSETS_ECERT_FILTER_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/filter.svg';

  /// {@macro assets_generator.ASSETS_ECERT_GLOBE_02_SVG.preview}
  static String get ASSETS_ECERT_GLOBE_02_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/globe-02.svg';

  /// {@macro assets_generator.ASSETS_ECERT_HEADPHONES_01_SVG.preview}
  static String get ASSETS_ECERT_HEADPHONES_01_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/headphones-01.svg';

  /// {@macro assets_generator.ASSETS_ECERT_ICONAPP_SVG.preview}
  static String get ASSETS_ECERT_ICONAPP_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/iconApp.svg';

  /// {@macro assets_generator.ASSETS_ECERT_ICONCTS_SVG.preview}
  static String get ASSETS_ECERT_ICONCTS_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/iconCTS.svg';

  /// {@macro assets_generator.ASSETS_ECERT_ICONNEXTSTEP_SVG.preview}
  static String get ASSETS_ECERT_ICONNEXTSTEP_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/iconNextStep.svg';

  /// {@macro assets_generator.ASSETS_ECERT_ICONUSER_SVG.preview}
  static String get ASSETS_ECERT_ICONUSER_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/iconUser.svg';

  /// {@macro assets_generator.ASSETS_ECERT_IMAGE_ADD_SVG.preview}
  static String get ASSETS_ECERT_IMAGE_ADD_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/image-add.svg';

  /// {@macro assets_generator.ASSETS_ECERT_IMAGE_UPLOAD_FILL_BORDER_SVG.preview}
  static String get ASSETS_ECERT_IMAGE_UPLOAD_FILL_BORDER_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/image-upload-fill-border.svg';

  /// {@macro assets_generator.ASSETS_ECERT_IMAGE_UPLOAD_FILL_SVG.preview}
  static String get ASSETS_ECERT_IMAGE_UPLOAD_FILL_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/image-upload-fill.svg';

  /// {@macro assets_generator.ASSETS_ECERT_IMAGEHOME_PNG.preview}
  static String get ASSETS_ECERT_IMAGEHOME_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/imageHome.png';

  /// {@macro assets_generator.ASSETS_ECERT_IMGSTEP1_PNG.preview}
  static String get ASSETS_ECERT_IMGSTEP1_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/imgStep1.png';

  /// {@macro assets_generator.ASSETS_ECERT_IMGSTEP2_PNG.preview}
  static String get ASSETS_ECERT_IMGSTEP2_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/imgStep2.png';

  /// {@macro assets_generator.ASSETS_ECERT_IMGSTEP3_PNG.preview}
  static String get ASSETS_ECERT_IMGSTEP3_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/imgStep3.png';

  /// {@macro assets_generator.ASSETS_ECERT_IMGSTEP4_PNG.preview}
  static String get ASSETS_ECERT_IMGSTEP4_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/imgStep4.png';

  /// {@macro assets_generator.ASSETS_ECERT_IMGSTEPCCCD1_PNG.preview}
  static String get ASSETS_ECERT_IMGSTEPCCCD1_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/imgStepCCCD1.png';

  /// {@macro assets_generator.ASSETS_ECERT_IMGSTEPCCCD2_PNG.preview}
  static String get ASSETS_ECERT_IMGSTEPCCCD2_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/imgStepCCCD2.png';

  /// {@macro assets_generator.ASSETS_ECERT_IMGSTEPCCCD3_PNG.preview}
  static String get ASSETS_ECERT_IMGSTEPCCCD3_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/imgStepCCCD3.png';

  /// {@macro assets_generator.ASSETS_ECERT_LINK_SVG.preview}
  static String get ASSETS_ECERT_LINK_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/link.svg';

  /// {@macro assets_generator.ASSETS_ECERT_MAIL_LINE_SVG.preview}
  static String get ASSETS_ECERT_MAIL_LINE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/mail-line.svg';

  /// {@macro assets_generator.ASSETS_ECERT_ORG_SVG.preview}
  static String get ASSETS_ECERT_ORG_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/org.svg';

  /// {@macro assets_generator.ASSETS_ECERT_PASSWORD_SVG.preview}
  static String get ASSETS_ECERT_PASSWORD_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/password.svg';

  /// {@macro assets_generator.ASSETS_ECERT_PRICE_EXPIRE_SVG.preview}
  static String get ASSETS_ECERT_PRICE_EXPIRE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/price-expire.svg';

  /// {@macro assets_generator.ASSETS_ECERT_PROFILE_SVG.preview}
  static String get ASSETS_ECERT_PROFILE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/profile.svg';

  /// {@macro assets_generator.ASSETS_ECERT_SEARCH_SVG.preview}
  static String get ASSETS_ECERT_SEARCH_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/search.svg';

  /// {@macro assets_generator.ASSETS_ECERT_SERI_SVG.preview}
  static String get ASSETS_ECERT_SERI_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/seri.svg';

  /// {@macro assets_generator.ASSETS_ECERT_TAX_CODE_SVG.preview}
  static String get ASSETS_ECERT_TAX_CODE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/tax_code.svg';

  /// {@macro assets_generator.ASSETS_ECERT_UPLOADIMG_PNG.preview}
  static String get ASSETS_ECERT_UPLOADIMG_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/uploadImg.png';

  /// {@macro assets_generator.ASSETS_ECERT_UPLOAD_DKKD_PNG.preview}
  static String get ASSETS_ECERT_UPLOAD_DKKD_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/eCert/upload_DKKD.png';

  static String get ASSETS_FONT_ARIAL_TTF =>
      '${isFromModules ? "packages/$package/" : ""}assets/font/Arial.ttf';

  static String get ASSETS_FONT_BOOKMAN_TTF =>
      '${isFromModules ? "packages/$package/" : ""}assets/font/Bookman.ttf';

  static String get ASSETS_FONT_CALIBRI_TTF =>
      '${isFromModules ? "packages/$package/" : ""}assets/font/Calibri.ttf';

  static String get ASSETS_FONT_COURIERNEW_TTF =>
      '${isFromModules ? "packages/$package/" : ""}assets/font/CourierNew.ttf';

  static String get ASSETS_FONT_FSJUSTAWESOMESCRIPT_OTF =>
      '${isFromModules ? "packages/$package/" : ""}assets/font/FSJustAwesomeScript.otf';

  static String get ASSETS_FONT_FZBELOVEDSCRIPT_TTF =>
      '${isFromModules ? "packages/$package/" : ""}assets/font/FzBelovedScript.ttf';

  static String get ASSETS_FONT_GARAMOND_TTF =>
      '${isFromModules ? "packages/$package/" : ""}assets/font/Garamond.ttf';

  static String get ASSETS_FONT_GEORGIA_TTF =>
      '${isFromModules ? "packages/$package/" : ""}assets/font/Georgia.ttf';

  static String get ASSETS_FONT_HLTROLLINGPEN_TTF =>
      '${isFromModules ? "packages/$package/" : ""}assets/font/HLTRollingPen.ttf';

  static String get ASSETS_FONT_HELVETICA_TTF =>
      '${isFromModules ? "packages/$package/" : ""}assets/font/Helvetica.ttf';

  static String get ASSETS_FONT_MONTEREYSCRIPTVH_OTF =>
      '${isFromModules ? "packages/$package/" : ""}assets/font/MontereyScriptVH.otf';

  static String get ASSETS_FONT_NVNFUNKYSIGNATURE_REGULAR_TTF =>
      '${isFromModules ? "packages/$package/" : ""}assets/font/NVNFunkySignature-Regular.ttf';

  static String get ASSETS_FONT_NVNNEOGRAPHY_TTF =>
      '${isFromModules ? "packages/$package/" : ""}assets/font/NVNNeography.ttf';

  static String get ASSETS_FONT_SHIMOGENAGNES_TTF =>
      '${isFromModules ? "packages/$package/" : ""}assets/font/SHImogenAgnes.ttf';

  static String get ASSETS_FONT_SVN_ASTRONOUT_OTF =>
      '${isFromModules ? "packages/$package/" : ""}assets/font/SVN-Astronout.otf';

  static String get ASSETS_FONT_SVN_BELLWETHERS_OTF =>
      '${isFromModules ? "packages/$package/" : ""}assets/font/SVN-Bellwethers.otf';

  static String get ASSETS_FONT_SVNTAKENBYVULTURES_OTF =>
      '${isFromModules ? "packages/$package/" : ""}assets/font/SVNTakenByVultures.otf';

  static String get ASSETS_FONT_TAHOMA_TTF =>
      '${isFromModules ? "packages/$package/" : ""}assets/font/Tahoma.ttf';

  static String get ASSETS_FONT_TIMESNEWROMAN_TTF =>
      '${isFromModules ? "packages/$package/" : ""}assets/font/TimesNewRoman.ttf';

  static String get ASSETS_FONT_VERDANA_TTF =>
      '${isFromModules ? "packages/$package/" : ""}assets/font/Verdana.ttf';

  static String get ASSETS_FONT_ICIELARTSY_RAWPLAIN_REGULAR_OTF =>
      '${isFromModules ? "packages/$package/" : ""}assets/font/iCielArtsy_RawPlain-Regular.otf';

  static String get ASSETS_FONT_ICIELFINCH_OTF =>
      '${isFromModules ? "packages/$package/" : ""}assets/font/iCielFinch.otf';

  static String get ASSETS_FONT_ICIELHIPSTERIA_TTF =>
      '${isFromModules ? "packages/$package/" : ""}assets/font/iCielHipsteria.ttf';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_BACKGROUND_BUTTON_NUMBER_WHITE_PNG.preview}
  static String
      get ASSETS_IMAGES_ICON_ICON_PNG_BACKGROUND_BUTTON_NUMBER_WHITE_PNG =>
          '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_png/background_button_number_white.png';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_IC_INSTRUCT_NUMBER1_PNG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_PNG_IC_INSTRUCT_NUMBER1_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_png/ic_instruct_number1.png';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_IC_INSTRUCT_NUMBER2_PNG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_PNG_IC_INSTRUCT_NUMBER2_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_png/ic_instruct_number2.png';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_IC_INSTRUCT_NUMBER2_CTS_PNG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_PNG_IC_INSTRUCT_NUMBER2_CTS_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_png/ic_instruct_number2_cts.png';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_IC_INSTRUCT_NUMBER3_PNG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_PNG_IC_INSTRUCT_NUMBER3_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_png/ic_instruct_number3.png';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_ICON_CORNER_LEFT_DOWN_PNG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_PNG_ICON_CORNER_LEFT_DOWN_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_png/icon_corner_left_down.png';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_ICON_CORNER_LEFT_UP_PNG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_PNG_ICON_CORNER_LEFT_UP_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_png/icon_corner_left_up.png';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_ICON_CORNER_RIGHT_DOWN_PNG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_PNG_ICON_CORNER_RIGHT_DOWN_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_png/icon_corner_right_down.png';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_ICON_CORNER_RIGHT_UP_PNG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_PNG_ICON_CORNER_RIGHT_UP_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_png/icon_corner_right_up.png';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_ICON_FACEID_PNG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_PNG_ICON_FACEID_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_png/icon_faceid.png';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_IMAGE_DEFAULT_JPG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_PNG_IMAGE_DEFAULT_JPG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_png/image_default.jpg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_IMG_ACCOUNT_PNG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_PNG_IMG_ACCOUNT_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_png/img_account.png';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_IMG_BANNER_NFC_PNG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_PNG_IMG_BANNER_NFC_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_png/img_banner_nfc.png';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_IMG_STOP_QR_PNG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_PNG_IMG_STOP_QR_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_png/img_stop_qr.png';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ERROR_SVGREPO_COM_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ERROR_SVGREPO_COM_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/error-svgrepo-com.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_2ID_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_2ID_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_2id.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_ADD_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_ADD_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_add.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_ADD_IMAGE_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_ADD_IMAGE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_add_image.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_ADD_ITEM_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_ADD_ITEM_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_add_item.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_ADD_PERSON_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_ADD_PERSON_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_add_person.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_ADD_SIGN_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_ADD_SIGN_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_add_sign.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_ADD_TAKE_PICTURE_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_ADD_TAKE_PICTURE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_add_take_picture.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_ADDRESS_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_ADDRESS_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_address.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_ATTACHMENT_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_ATTACHMENT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_attachment.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_ATTACHMENT_EMPTY_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_ATTACHMENT_EMPTY_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_attachment_empty.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_AUTHORITY_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_AUTHORITY_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_authority.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_BANNER_RESET_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_BANNER_RESET_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_banner_reset.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_BANNER_RESET_EMAIL_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_BANNER_RESET_EMAIL_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_banner_reset_email.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_BANNER_SIGN_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_BANNER_SIGN_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_banner_sign.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_BORDER_PICTURE_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_BORDER_PICTURE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_border_picture.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_CART_CTS_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_CART_CTS_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_cart_cts.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_CART_CTS_BUTTON_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_CART_CTS_BUTTON_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_cart_cts_button.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_CHANGE_PASSWORD_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_CHANGE_PASSWORD_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_change_password.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_CHANGEPASS_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_CHANGEPASS_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_changepass.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_COMPANY_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_COMPANY_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_company.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_DATE_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_DATE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_date.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_EMAIL_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_EMAIL_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_email.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_EMPTY_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_EMPTY_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_empty.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_EMPTY_SIGN_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_EMPTY_SIGN_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_empty_sign.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_ERROR_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_ERROR_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_error.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_ERROR_SNACKBAR_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_ERROR_SNACKBAR_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_error_snackbar.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_FACEID_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_FACEID_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_faceid.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_FILTER_ACTIVE_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_FILTER_ACTIVE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_filter_active.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_FINGERPRINT_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_FINGERPRINT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_fingerprint.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_INFO_SIGN_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_INFO_SIGN_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_info_sign.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_INFO_SIGN_DETAIL_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_INFO_SIGN_DETAIL_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_info_sign_detail.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_INSTRUCT_NEXT_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_INSTRUCT_NEXT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_instruct_next.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_JOB_ALL_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_JOB_ALL_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_job_all.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_KY_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_KY_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_ky.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_LOGO_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_LOGO_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_logo.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_LOGOUT_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_LOGOUT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_logout.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_MENU_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_MENU_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_menu.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_MESSAGE_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_MESSAGE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_message.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_MESSAGE_EMPTY_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_MESSAGE_EMPTY_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_message_empty.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_MORE_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_MORE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_more.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_NEXT_PAGE_ENABEL_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_NEXT_PAGE_ENABEL_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_next_page_enabel.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_NOTIFICATION_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_NOTIFICATION_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_notification.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_OVERDUE_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_OVERDUE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_overdue.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_OVERVIEW_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_OVERVIEW_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_overview.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_PASS_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_PASS_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_pass.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_PHONE_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_PHONE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_phone.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_POSITION_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_POSITION_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_position.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_PREVIOUS_PAGE_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_PREVIOUS_PAGE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_previous_page.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_PREVIOUS_PAGE_ENABEL_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_PREVIOUS_PAGE_ENABEL_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_previous_page_enabel.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_PROCESSED_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_PROCESSED_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_processed.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_REMOVE_INFO_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_REMOVE_INFO_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_remove_info.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_SETUP_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_SETUP_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_setup.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_SHOW_MENU_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_SHOW_MENU_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_show_menu.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_SIGN_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_SIGN_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_sign.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_SUCCESS_SNACKBAR_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_SUCCESS_SNACKBAR_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_success_snackbar.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_SUPPORT_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_SUPPORT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_support.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_SUPPORT_BANNER_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_SUPPORT_BANNER_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_support_banner.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_SUPPORT_EMAIL_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_SUPPORT_EMAIL_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_support_email.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_SUPPORT_HOME_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_SUPPORT_HOME_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_support_home.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_SUPPORT_LOCATION_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_SUPPORT_LOCATION_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_support_location.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_SUPPORT_PHONE_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_SUPPORT_PHONE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_support_phone.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_SUPPORT_WEB_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_SUPPORT_WEB_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_support_web.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_UNPROCESSED_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_UNPROCESSED_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_unprocessed.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_USERNAME_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_USERNAME_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_username.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_VIEW_PDF_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_VIEW_PDF_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_view_pdf.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_WARNING_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_WARNING_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_warning.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_ADD_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_ADD_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_add.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_BACK_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_BACK_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_back.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_BACKWARD_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_BACKWARD_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_backward.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_BOLD_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_BOLD_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_bold.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_CANCEL_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_CANCEL_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_cancel.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_CANCEL_AUTHENTICATION_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_CANCEL_AUTHENTICATION_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_cancel_authentication.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_CAPTURES_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_CAPTURES_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_captures.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_CHECKBOX_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_CHECKBOX_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_checkbox.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_CHECKBOX_EMPTY_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_CHECKBOX_EMPTY_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_checkbox_empty.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_CHECKBOX_TICK_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_CHECKBOX_TICK_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_checkbox_tick.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_CHOOSE_STYLE_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_CHOOSE_STYLE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_choose_style.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_CLEAR_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_CLEAR_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_clear.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_COMPLETE_SENT_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_COMPLETE_SENT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_complete_sent.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DETAILS_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_DETAILS_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_details.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DETAILS_SELECT_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_DETAILS_SELECT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_details_select.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DIGI_CERT_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_DIGI_CERT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_digi_cert.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOC_ICON_DOC_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOC_ICON_DOC_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_doc/icon_doc.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOC_ICON_DOC_COMPLETE_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOC_ICON_DOC_COMPLETE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_doc/icon_doc_complete.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOC_ICON_DOC_OVERDU_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOC_ICON_DOC_OVERDU_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_doc/icon_doc_overdu.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOC_ICON_DOC_PROCESS_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOC_ICON_DOC_PROCESS_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_doc/icon_doc_process.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOC_ICON_DOC_REFUSE_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOC_ICON_DOC_REFUSE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_doc/icon_doc_refuse.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOC_ICON_FILE_ATTACHED_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOC_ICON_FILE_ATTACHED_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_doc/icon_file_attached.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_docs.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_BLACK_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_BLACK_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_docs_black.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_DELETED_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_DELETED_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_docs_deleted.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_DELETED_BLACK_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_DELETED_BLACK_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_docs_deleted_black.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_DRAFT_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_DRAFT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_docs_draft.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_DRAFT_BLACK_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_DRAFT_BLACK_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_docs_draft_black.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_SENT_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_SENT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_docs_sent.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_SENT_BLACK_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_SENT_BLACK_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_docs_sent_black.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCUMENT_WORD_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCUMENT_WORD_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_document_word.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DONE_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_DONE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_done.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOWNLOAD_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOWNLOAD_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_download.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DRAW_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_DRAW_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_draw.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_EDIT_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_EDIT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_edit.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_EDIT_PEN_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_EDIT_PEN_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_edit_pen.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_ELLIPSE_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_ELLIPSE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_ellipse.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_EYE_OFF_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_EYE_OFF_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_eye_off.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_EYE_ON_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_EYE_ON_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_eye_on.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FACE_BETWEEN_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_FACE_BETWEEN_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_face_between.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FACE_BLINK_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_FACE_BLINK_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_face_blink.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FACE_DOWN_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_FACE_DOWN_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_face_down.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FACE_LEFT_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_FACE_LEFT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_face_left.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FACE_RIGHT_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_FACE_RIGHT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_face_right.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FACE_SMILE_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_FACE_SMILE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_face_smile.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FACE_UP_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_FACE_UP_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_face_up.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FILTER_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_FILTER_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_filter.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FLASH_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_FLASH_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_flash.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FLASH_OFF_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_FLASH_OFF_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_flash_off.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FORDWARD_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_FORDWARD_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_fordward.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_HOME_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_HOME_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_home.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_HOME_SELECT_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_HOME_SELECT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_home_select.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_IMAGE_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_IMAGE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_image.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_INFORMATION_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_INFORMATION_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_information.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_ITALIC_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_ITALIC_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_italic.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_KYC_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_KYC_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_kyc.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_LOGO_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_LOGO_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_logo.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_LOGOUT_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_LOGOUT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_logout.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_MARK_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_MARK_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_mark.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_MENU_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_MENU_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_menu.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_MENU_ADD_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_MENU_ADD_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_menu_add.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_MORE_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_MORE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_more.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_NO_SUPPORT_NFC_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_NO_SUPPORT_NFC_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_no_support_nfc.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_NOTI_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_NOTI_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_noti.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_NOTIFICATION_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_NOTIFICATION_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_notification.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_PAGE_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_PAGE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_page.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_PDF_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_PDF_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_pdf.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_PEN_WRITING_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_PEN_WRITING_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_pen_writing.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_PROFILE_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_PROFILE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_profile.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_PROFILE_SELECT_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_PROFILE_SELECT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_profile_select.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_RED_CANCEL_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_RED_CANCEL_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_red_cancel.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_REJECT_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_REJECT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_reject.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_SAVE_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_SAVE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_save.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_SCAN_NFC_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_SCAN_NFC_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_scan_nfc.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_SEARCH_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_SEARCH_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_search.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_SECURITY_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_SECURITY_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_security.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_SEE_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_SEE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_see.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_SENT_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_SENT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_sent.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_SHARE_DOCUMENT_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_SHARE_DOCUMENT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_share_document.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_SUPPORT_NFC_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_SUPPORT_NFC_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_support_nfc.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_TIME_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_TIME_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_time.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_TRASH_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_TRASH_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_trash.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_UP_IMAGE_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_UP_IMAGE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_up_image.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_UPLOAD_IMAGE_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_UPLOAD_IMAGE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_upload_image.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_VIEW_PDF_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_VIEW_PDF_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_view_pdf.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_WARNING_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_WARNING_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_warning.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IXEX_NEXT_PAGE_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IXEX_NEXT_PAGE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ixex_next_page.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_NOTIFICATION_13_SVGREPO_COM_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_NOTIFICATION_13_SVGREPO_COM_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/notification-13-svgrepo-com.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_SUCCESS_STANDARD_SVGREPO_COM_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_SUCCESS_STANDARD_SVGREPO_COM_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/success-standard-svgrepo-com.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_WARNING_SVGREPO_COM_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_WARNING_SVGREPO_COM_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/warning-svgrepo-com.svg';

  static String get ASSETS_LOCALES_VI_VN_JSON =>
      '${isFromModules ? "packages/$package/" : ""}assets/locales/vi_VN.json';
}
